Repository atj393/promt-save-reuse-chatgpt-and-gemini, pull requests merged in 2024-10, with the labels that each got.

#31 Update content.js
  content.js
Labels: hacktoberfest

#26 enhancement: Add Error Handling for Missing Input Fields
  background.js
  manifest.json
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#35 Create USER_GUIDE.md
  USER_GUIDE.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
